### ISSUE TITLE
Sponsors page

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2017.texascamp.org-react#19]
And find more sponsors?

**Comment by rocketeerbkw** [comment]
I've added sponor and sponsorgroup components and added all the current sponsors. Still left to do for this page is to finish my poor first pass at styling it correctly. Here's the example of what it should look like http://preview.amazeelabs.com/texas-camp/website/finals/f/sponsors.gif.

**Comment by ccjjmartin** [comment]
Only thing left here looks like Jeff's #45, closing this one.
