### ISSUE TITLE
Brand the site

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2017.texascamp.org-react#31]
We need to adjust the entire look and feel of the site to use the color schemes, font sizes, and fonts provided by Andrew.

**Comment by rocketeerbkw** [comment]
Depends on #33

**Comment by unamaria** [comment]
Done?

**Comment by ccjjmartin** [comment]
Yes, I think Andrew gave us specifics here that you have already implemented (links, fonts, etc).  Thanks!
