### ISSUE TITLE
Decrease opacity for legibility, should be about 90% transparent

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2017.texascamp.org-react#57]
http://preview.amazeelabs.com/texas-camp/website/finals/f/texas-camp-review.jpg

**Comment by unamaria** [comment]
Closing, done by @ccjjmartin ([commit](https://github.com/TexasCamp/2017.texascamp.org-react/commit/cb3f46e16567d2976dcc4594e5d385a69e1e2de0)).
